test cicd

diff --git a/.github/workflows/baseline-cd-testing.yaml b/.github/workflows/baseline-cd-testing.yaml
--- a/.github/workflows/baseline-cd-testing.yaml
+++ b/.github/workflows/baseline-cd-testing.yaml
@@ -180,44 +180,44 @@ jobs:
         working-directory: ${{ env.TF_DIR }}
         run: terraform apply -auto-approve -no-color tfplan
 
-      # - name: Initial RDS
-      #   working-directory: ${{ env.TF_DIR }}
-      #   env:
-      #     AWS_REGION: ${{ vars.AWS_REGION }}
-      #   run: |
-      #     set -euo pipefail
+      - name: Initial RDS
+        working-directory: ${{ env.TF_DIR }}
+        env:
+          AWS_REGION: ${{ vars.AWS_REGION }}
+        run: |
+          set -euo pipefail
 
-      #     PARAMS_JSON="$(terraform output -json flyway_task_param)"
+          PARAMS_JSON="$(terraform output -json flyway_task_param)"
 
-      #     CLUSTER=$(echo "$PARAMS_JSON" | jq -r '.cluster')
-      #     TASK_DEF=$(echo "$PARAMS_JSON" | jq -r '.task_definition')
-      #     LAUNCH_TYPE=$(echo "$PARAMS_JSON" | jq -r '.launch_type')
-      #     SUBNETS=$(echo "$PARAMS_JSON" | jq -r '.subnets | join(",")')
-      #     SGS=$(echo "$PARAMS_JSON" | jq -r '.security_groups | join(",")')
+          CLUSTER=$(echo "$PARAMS_JSON" | jq -r '.cluster')
+          TASK_DEF=$(echo "$PARAMS_JSON" | jq -r '.task_definition')
+          LAUNCH_TYPE=$(echo "$PARAMS_JSON" | jq -r '.launch_type')
+          SUBNETS=$(echo "$PARAMS_JSON" | jq -r '.subnets | join(",")')
+          SGS=$(echo "$PARAMS_JSON" | jq -r '.security_groups | join(",")')
 
-      #     echo "Cluster: $CLUSTER"
-      #     echo "Task definition: $TASK_DEF"
-      #     echo "Subnets ID: $SUBNETS"
-      #     echo "Security groups ID: $SGS"
+          echo "Cluster: $CLUSTER"
+          echo "Task definition: $TASK_DEF"
+          echo "Subnets ID: $SUBNETS"
+          echo "Security groups ID: $SGS"
 
-      #     TASK_ARN=$(
-      #       aws ecs run-task \
-      #         --cluster "$CLUSTER" \
-      #         --task-definition "$TASK_DEF" \
-      #         --launch-type "$LAUNCH_TYPE" \
-      #         --network-configuration "awsvpcConfiguration={subnets=[$SUBNETS],securityGroups=[$SGS]}" \
-      #         --region "$AWS_REGION" \
-      #         --query 'tasks[0].taskArn' \
-      #         --output text
-      #     )
+          TASK_ARN=$(
+            aws ecs run-task \
+              --cluster "$CLUSTER" \
+              --task-definition "$TASK_DEF" \
+              --launch-type "$LAUNCH_TYPE" \
+              --network-configuration "awsvpcConfiguration={subnets=[$SUBNETS],securityGroups=[$SGS]}" \
+              --region "$AWS_REGION" \
+              --query 'tasks[0].taskArn' \
+              --output text
+          )
 
-      #     echo "Waiting for Flyway task to finish..."
-      #     aws ecs wait tasks-stopped \
-      #       --cluster "$CLUSTER" \
-      #       --tasks "$TASK_ARN" \
-      #       --region "$AWS_REGION"
+          echo "Waiting for Flyway task to finish..."
+          aws ecs wait tasks-stopped \
+            --cluster "$CLUSTER" \
+            --tasks "$TASK_ARN" \
+            --region "$AWS_REGION"
 
-      #     echo "Flyway migration task completed successfully."
+          echo "Flyway migration task completed successfully."
 
       - name: Send email notification
         if: failure()
@@ -269,7 +269,7 @@ jobs:
 
       - name: Wait for DNS
         run: |
-          sleep 120
+          sleep 600
 
       - name: Setup K6
         uses: grafana/setup-k6-action@v1
@@ -551,108 +551,108 @@ jobs:
           attachments: |
             k6-reports-all/**/*.html
 
-  destroy:
-    name: Baseline-Destroy
-    needs: notification
-    if: always()
-    runs-on: ubuntu-latest
-    timeout-minutes: 30
-    environment: baseline
-    env:
-      TF_DIR: aws/sol_${{vars.ENV}}
-      TF_PLUGIN_CACHE_DIR: /home/runner/.terraform.d/plugin-cache
-      TF_VAR_aws_region: ${{ vars.AWS_REGION }}
-      TF_VAR_env: ${{ vars.ENV }}
-      TF_VAR_db_name: ${{ secrets.DB_NAME }}
-      TF_VAR_db_username: ${{ secrets.DB_USERNAME }}
-      TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
-      TF_VAR_db_app_pwd: ${{ secrets.DB_APP_PWD }}
-      TF_VAR_db_readonly_pwd: ${{ secrets.DB_READONLY_PWD }}
-      TF_VAR_cloudflare_api_token: ${{ secrets.CF_API_TOKEN }}
-      TF_VAR_cloudflare_zone_id: ${{ secrets.CF_ZONE_ID }}
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
+  # destroy:
+  #   name: Baseline-Destroy
+  #   needs: notification
+  #   if: always()
+  #   runs-on: ubuntu-latest
+  #   timeout-minutes: 30
+  #   environment: baseline
+  #   env:
+  #     TF_DIR: aws/sol_${{vars.ENV}}
+  #     TF_PLUGIN_CACHE_DIR: /home/runner/.terraform.d/plugin-cache
+  #     TF_VAR_aws_region: ${{ vars.AWS_REGION }}
+  #     TF_VAR_env: ${{ vars.ENV }}
+  #     TF_VAR_db_name: ${{ secrets.DB_NAME }}
+  #     TF_VAR_db_username: ${{ secrets.DB_USERNAME }}
+  #     TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
+  #     TF_VAR_db_app_pwd: ${{ secrets.DB_APP_PWD }}
+  #     TF_VAR_db_readonly_pwd: ${{ secrets.DB_READONLY_PWD }}
+  #     TF_VAR_cloudflare_api_token: ${{ secrets.CF_API_TOKEN }}
+  #     TF_VAR_cloudflare_zone_id: ${{ secrets.CF_ZONE_ID }}
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v4
 
-      - name: Setup Terraform
-        uses: hashicorp/setup-terraform@v3
-        with:
-          terraform_version: ${{ vars.TF_VERSION }}
+  #     - name: Setup Terraform
+  #       uses: hashicorp/setup-terraform@v3
+  #       with:
+  #         terraform_version: ${{ vars.TF_VERSION }}
 
-      - name: Configure AWS credentials (OIDC)
-        uses: aws-actions/configure-aws-credentials@v4
-        with:
-          role-to-assume: ${{ secrets.AWS_TF_ROLE_ARN}}
-          aws-region: ${{ vars.AWS_REGION }}
+  #     - name: Configure AWS credentials (OIDC)
+  #       uses: aws-actions/configure-aws-credentials@v4
+  #       with:
+  #         role-to-assume: ${{ secrets.AWS_TF_ROLE_ARN}}
+  #         aws-region: ${{ vars.AWS_REGION }}
 
-      - name: Configure Terraform plugin cache
-        run: |
-          mkdir -pv ${{ env.TF_PLUGIN_CACHE_DIR }}
-          echo 'plugin_cache_dir = "${{ env.TF_PLUGIN_CACHE_DIR }}"' > ~/.terraformrc
+  #     - name: Configure Terraform plugin cache
+  #       run: |
+  #         mkdir -pv ${{ env.TF_PLUGIN_CACHE_DIR }}
+  #         echo 'plugin_cache_dir = "${{ env.TF_PLUGIN_CACHE_DIR }}"' > ~/.terraformrc
 
-      - name: Cache Terraform plugins
-        uses: actions/cache@v4
-        with:
-          path: ${{ env.TF_PLUGIN_CACHE_DIR }}
-          key: ${{ runner.os }}-terraform-${{ vars.TF_VERSION }}-${{ hashFiles('aws/.terraform.lock.hcl') }}
+  #     - name: Cache Terraform plugins
+  #       uses: actions/cache@v4
+  #       with:
+  #         path: ${{ env.TF_PLUGIN_CACHE_DIR }}
+  #         key: ${{ runner.os }}-terraform-${{ vars.TF_VERSION }}-${{ hashFiles('aws/.terraform.lock.hcl') }}
 
-      - name: Terraform init - S3 backend
-        working-directory: ${{ env.TF_DIR }}
-        run: |
-          terraform init -reconfigure -input=false \
-            -backend-config="bucket=${{ vars.AWS_BACKEND_BUCKET }}" \
-            -backend-config="region=${{ vars.AWS_REGION }}" \
-            -backend-config="key=${{ vars.PROJECT }}/${{ vars.ENV }}/terraform.tfstate" \
-            -backend-config="encrypt=true"
+  #     - name: Terraform init - S3 backend
+  #       working-directory: ${{ env.TF_DIR }}
+  #       run: |
+  #         terraform init -reconfigure -input=false \
+  #           -backend-config="bucket=${{ vars.AWS_BACKEND_BUCKET }}" \
+  #           -backend-config="region=${{ vars.AWS_REGION }}" \
+  #           -backend-config="key=${{ vars.PROJECT }}/${{ vars.ENV }}/terraform.tfstate" \
+  #           -backend-config="encrypt=true"
 
-      - name: Terraform Validate
-        working-directory: ${{ env.TF_DIR }}
-        run: |
-          terraform fmt -check -recursive -no-color
-          terraform validate -no-color
+  #     - name: Terraform Validate
+  #       working-directory: ${{ env.TF_DIR }}
+  #       run: |
+  #         terraform fmt -check -recursive -no-color
+  #         terraform validate -no-color
 
-      - name: Destroy - Terraform Plan
-        working-directory: ${{ env.TF_DIR }}
-        id: destroy-plan
-        run: terraform plan -out=destroy-tfplan -input=false -no-color -destroy
+  #     - name: Destroy - Terraform Plan
+  #       working-directory: ${{ env.TF_DIR }}
+  #       id: destroy-plan
+  #       run: terraform plan -out=destroy-tfplan -input=false -no-color -destroy
 
-      - name: Destroy - Show plan (JSON)
-        working-directory: ${{ env.TF_DIR }}
-        run: terraform show -json destroy-tfplan > destroy-tfplan.json
+  #     - name: Destroy - Show plan (JSON)
+  #       working-directory: ${{ env.TF_DIR }}
+  #       run: terraform show -json destroy-tfplan > destroy-tfplan.json
 
-      - name: Destroy - Save plan artifacts
-        uses: actions/upload-artifact@v4
-        with:
-          name: tfplan-bundle-destroy
-          path: |
-            ${{ env.TF_DIR }}/destroy-tfplan
-            ${{ env.TF_DIR }}/destroy-tfplan.json
-          retention-days: 3
+  #     - name: Destroy - Save plan artifacts
+  #       uses: actions/upload-artifact@v4
+  #       with:
+  #         name: tfplan-bundle-destroy
+  #         path: |
+  #           ${{ env.TF_DIR }}/destroy-tfplan
+  #           ${{ env.TF_DIR }}/destroy-tfplan.json
+  #         retention-days: 3
 
-      - name: Destroy - Terraform Apply
-        working-directory: ${{ env.TF_DIR }}
-        run: terraform apply -auto-approve -no-color destroy-tfplan
+  #     - name: Destroy - Terraform Apply
+  #       working-directory: ${{ env.TF_DIR }}
+  #       run: terraform apply -auto-approve -no-color destroy-tfplan
 
-      - name: Send email notification
-        if: failure()
-        uses: dawidd6/action-send-mail@v3
-        with:
-          server_address: smtp.gmail.com
-          server_port: 465
-          secure: true
-          username: ${{ secrets.EMAIL_USERNAME }}
-          password: ${{ secrets.EMAIL_PASSWORD }}
-          subject: "${{ job.status }} - ${{ github.workflow }}: ${{ vars.PROJECT}} (${{vars.ENV}})"
-          to: ${{ secrets.EMAIL_USERNAME }}
-          from: ${{ secrets.EMAIL_USERNAME }}
-          html_body: |
-            <h2>GitHub Actions CI/CD Notification</h2>
-            <p><b>Project</b>: ${{ vars.PROJECT}}</p>
-            <p><b>Repository</b>: ${{ github.repository }}</p>
-            <p><b>Env</b>: ${{ vars.ENV }}</p>
-            <p><b>Job</b>: ${{ github.job }}</p>
-            <p><b>Status</b>: ${{ job.status }}</p>
-            <p><b>Branch</b>: ${{ github.ref }}</p>
-            <p><b>Workflow</b>: ${{ github.workflow }}</p>
-            <p><b>Commit</b>: ${{ github.sha }}</p>
-            <p><a href="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}">View Workflow Run</a></p>
+  #     - name: Send email notification
+  #       if: failure()
+  #       uses: dawidd6/action-send-mail@v3
+  #       with:
+  #         server_address: smtp.gmail.com
+  #         server_port: 465
+  #         secure: true
+  #         username: ${{ secrets.EMAIL_USERNAME }}
+  #         password: ${{ secrets.EMAIL_PASSWORD }}
+  #         subject: "${{ job.status }} - ${{ github.workflow }}: ${{ vars.PROJECT}} (${{vars.ENV}})"
+  #         to: ${{ secrets.EMAIL_USERNAME }}
+  #         from: ${{ secrets.EMAIL_USERNAME }}
+  #         html_body: |
+  #           <h2>GitHub Actions CI/CD Notification</h2>
+  #           <p><b>Project</b>: ${{ vars.PROJECT}}</p>
+  #           <p><b>Repository</b>: ${{ github.repository }}</p>
+  #           <p><b>Env</b>: ${{ vars.ENV }}</p>
+  #           <p><b>Job</b>: ${{ github.job }}</p>
+  #           <p><b>Status</b>: ${{ job.status }}</p>
+  #           <p><b>Branch</b>: ${{ github.ref }}</p>
+  #           <p><b>Workflow</b>: ${{ github.workflow }}</p>
+  #           <p><b>Commit</b>: ${{ github.sha }}</p>
+  #           <p><a href="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}">View Workflow Run</a></p>
